### ISSUE TITLE
undefined method `newTrueColor' for GD::Image:Class

### ISSUE THREAD

**Issue by skoder** [amardaxini/rchart#1]
Hello. I can't get work your gem. I'm using rvm and new Ubuntu 10.10.
I tried with ruby 1.8.7@rails2, ruby 1.8.7@rails3 and 1.9.2@rails3 (but for ruby 1.9.2 I had to use this fork of ruby-gd: http://github.com/Spakman/ruby-gd )
In all cases I got error while trying to render example1.rb from http://github.com/amardaxini/rchart_examples:

NoMethodError (undefined method `newTrueColor' for GD::Image:Class):
  rchart (1.1.1) lib/rchart.rb:99:in`initialize'

gems:

rchart (1.1.1)
ruby-gd (0.8.0)

$ ruby -v
ruby 1.8.7 (2010-08-16 patchlevel 302) [i686-linux]
$ rails -v
Rails 2.3.9

deb packages installed: 
ruby-gd version 0.7.4.1-6
libpng12-dev (used instead of libpng in new ubuntu) version 1.2.44-1
libgd2-xpm-dev version 2.0.36~rc1~dfsg-3.2ubuntu1

Cheers

**Comment by amardaxini** [comment]
Hi,
I have just forked  Spakman-ruby-gd gem and done some necessary changes in GD.c file
Uninstall ruby-gd gem and install from http://github.com/amardaxini/ruby-gd
And try to run 
ruby extconf.rb --with-xpm --with-ttf --with-freetype --with-jpeg  --enable-gd2_0
then rake gem,gem install pkg/ruby-gd-0.8.0.gem
Try this if you have any issue you can ping me again
Thanks.

**Comment by skoder** [comment]
Thank you for reply.
Unfortunately, this still not works. 
I removed old ruby-gd, then cloned git repo of your fork of ruby-gd. Then ran command 
ruby extconf.rb --with-xpm --with-ttf --with-freetype --with-jpeg --enable-gd2_0
Command rake gem returned error:
rake aborted!
undefined method `manage_gems' for Gem:Module
/home/fabian/ruby/gems/ruby-gd/Rakefile:2

I removed 'manage_gems' line in Rakefile and rake gem created gem file. I installed this file, but this didn't help, I still got error undefined method `newTrueColor' for GD::Image:Class in all my 3 environments - 1.8.7@rails2, 1.8.7@rails3 and 1.9.2@rails3

**Comment by amardaxini** [comment]
Have you install GD2 library,For ruby 1-8.7 try to install ruby-gd from ruby gems or
rubyforge.
After installing gem,or download gem and try this
and then install gem
ruby extconf.rb --with-xpm --with-ttf --with-freetype --with-jpeg --enable-gd2_0
You have to do make and make install
So GD.so file is placed on proper path
newTrueColor method is available GD2 onwards therfore we have to enable gd2
If this is not worked ping me 
Thanks

**Comment by skoder** [comment]
Yay! It works!
By steps:
0. remove ruby-gd and rchart and install couple of packages from Ubuntu repository: libgdchart-gd2-xpm and libgdchart-gd2-xpm-dev (without these packages ruby-gd can make only without '--with-xpm' option)
1. install gd2: gem install gd2
2. Cloning you ruby-gd fork: git clone http://github.com/amardaxini/ruby-gd
3. go to ruby-gd folder and run: ruby extconf.rb --with-xpm --with-ttf --with-freetype --with-jpeg --enable-gd2_0
4. then run: make && make install
5. remove string 'Gem::manage_gems' from Rakefile
6. run 'rake gem'
6. run 'gem install pkg/ruby-gem-0.8.0.gem'
7. PROFIT!

Now gem works with 1.8.7@rails2, 1.8.7@rails3 and 1.9.2@rails3

Thank you for your support!

Also, I added your gem to railsplugins.org: http://www.railsplugins.org/plugins/576-rchart
